### ISSUE TITLE
custom style everything with optional css variables and fallbacks

### ISSUE THREAD

**Issue by russellsamora** [russellgoldenberg/svelte-crossword#10]
* focus color
* clue highlight color
* void color
* grid line color and weights
* border color and weights
* font family
* font size (relative to box)

**Comment by Wattenberger** [comment]
one thought I had here - it might be cleaner to use css variables instead

**Comment by russellsamora** [comment]
would it work like this? we would expose global vars (eg: --crossword-focus-color) and they could override them in their app styles?
